---
title: "Rank Estimate"
output: html_document
date: '2022-07-11'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r cars}
library(cowplot)
library(dplyr)
```

To aggregate the rank estimate results obtained from Python, we first consolidate the results following the steps below:
```{r pressure, echo=FALSE}
########################################################
# rank estimates - output from python 
  output_rank_estimate = "./rank_estimate/"

  typelist <- unique(unlist(lapply(dir(output_rank_estimate),function(x) strsplit(x,"_")[[1]][[1]])))
#rank_blank <- data.frame(cancertype=typelist,rank=NA,rss_suggested_rank=NA)
 
  for (i in 1:length(typelist)) {
    tryCatch({
      print(i)
      type <- typelist[i]
      
      estimate <- read.csv(file= paste0(output_rank_estimate,dir(output_rank_estimate)[stringr::str_detect(dir(output_rank_estimate),paste0(type,"_ccfFractionMatrix.csv"))])) 
      estimate_random <- read.csv(file=paste0(output_rank_estimate,dir(output_rank_estimate)[stringr::str_detect(dir(output_rank_estimate),paste0(type,"_ccfFractionMatrix.random.csv"))])) 
      estimate$Data ='normal'
      estimate_random$Data = 'random' 
      
      estimate_rank <- rbind(estimate,estimate_random) 
  
      xx <- reshape2::melt(estimate_rank,id=c("rank","Data")) %>% mutate(Measure=NA)
      xx$variable <- as.character(xx$variable)
      
      xx[which(xx$variable=="dispersion"),]$Measure <- "Best fit"
      xx[which(xx$variable=="cophenetic"),]$Measure <- "Consensus"
      xx[which(xx$variable=="sparseness1"),]$Measure <- "Basis"
      xx[which(xx$variable=="sparseness2"),]$Measure <- "Coefficients"
      xx[c(which(xx$variable=="sparseness2"),which(xx$variable=="sparseness1")),]$variable <- "sparseness"
      xx[which(xx$variable=="rss"),]$Measure <- "Best fit"
      xx[which(xx$variable=="evar"),]$Measure <- "Best fit"
      xx[which(xx$variable=="euclidean"),]$Measure <- "Best fit"
      xx[which(xx$variable=="kl"),]$Measure <- "Best fit"
      #xx <- subset(xx,variable %in% c("cophenetic","dispersion","rss","sparseness"))
      
      # rss_suggested_rank
      min_rank = min(xx$rank)
      idx = 1:(nrow(estimate)-1)
      rss_decrease <-  min_rank + which((estimate[order(estimate$rank),]$rss[idx]-estimate[order(estimate$rank),]$rss[idx+1]) - (estimate_random[order(estimate_random$rank),]$rss[idx]-estimate_random[order(estimate_random$rank),]$rss[idx+1])<0)[1]
      #rank_blank[which(rank_blank$cancertype == type),]$rss_suggested_rank <- rss_decrease 
    
      xx$cancertype = type
      xx$rss_suggested_rank <- rss_decrease 
      
      # Merge
      if (i==1) estimate_rank_all = xx
        else estimate_rank_all = rbind(estimate_rank_all,xx)
    })
  }

  #write.csv(estimate_rank_all,paste0(output_rank_estimate,"rank_estimate_all.csv"))

```

After obtaining the consolidated table, the next step involves visualizing the rank estimates to select the most suitable ranks for signature extraction.
```{r}
estimate_rank_all %>%
    filter(cancertype!="All") %>%
    mutate(label = paste0(cancertype," - ",variable)) %>%
    ggplot(aes(x=rank,y=value))+
    geom_line(aes(lty=Data,color=Measure),cex=1)+
    geom_point(aes(shape=Data,color=Measure),cex=2)+
    labs(title="NMF Rank Estimate")+
    scale_x_continuous(breaks = min(estimate_rank_all$rank):max(estimate_rank_all$rank))+
    facet_wrap(~label,scales = "free_y",ncol=7)+
    #facet_wrap(cancertype~variable,scales = "free_y",ncol=7)+
    theme_bw()+ 
    theme(#strip.background = element_rect(fill="orange"),
          strip.text = element_text(colour ="black"))
```